# Generated by Django 2.2.1 on 2019-06-16 14:17

import absolutum.mixins.mixins
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20190616_1417'),
        ('identity', '0001_initial'),
        ('deal', '0002_auto_20190616_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Кодовое имя')),
                ('label', models.CharField(max_length=128, verbose_name='Наименование')),
                ('template', models.TextField(verbose_name='Шаблон')),
            ],
            options={
                'ordering': ['label'],
                'verbose_name_plural': 'СМС: шаблоны',
                'permissions': [('add_smstemplate', 'Добавлять СМС: шаблон'), ('change_smstemplate', 'Редактировать СМС: шаблон'), ('delete_smstemplate', 'Удалять СМС: шаблон'), ('view_smstemplate', 'Просматривать СМС: шаблон')],
                'default_permissions': (),
                'verbose_name': 'СМС: шаблон',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait', 'Ожидает'), ('error', 'Ошибка'), ('done', 'Отправлено')], default='wait', max_length=32, verbose_name='Статус смс')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_sent', models.DateTimeField(blank=True, null=True, verbose_name='Время отправления')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal', verbose_name='Сделка')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.Person', verbose_name='Персона')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_created', to='company.User', verbose_name='Кто создал')),
            ],
            options={
                'ordering': ['-time_created'],
                'verbose_name_plural': 'СМС',
                'permissions': [('add_sms', 'Добавлять СМС'), ('change_sms', 'Редактировать СМС'), ('delete_sms', 'Удалять СМС'), ('view_sms', 'Просматривать СМС')],
                'default_permissions': (),
                'verbose_name': 'СМС',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
