# Generated by Django 2.2.1 on 2019-06-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='phone',
            field=models.CharField(default='', max_length=32, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sms',
            name='status_text',
            field=models.TextField(blank=True, verbose_name='Текст статуса'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидает'), ('error', 'Ошибка'), ('ok', 'Отправлено')], default='wait', max_length=32, verbose_name='Статус смс'),
        ),
    ]
