# Generated by Django 2.2.1 on 2019-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_sms_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидает'), ('error', 'Ошибка'), ('ok', 'Отправлено'), ('cancel', 'Отменена')], default='wait', max_length=32, verbose_name='Статус смс'),
        ),
    ]
