# Generated by Django 2.2.1 on 2019-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20190802_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Описание'),
        ),
    ]
