# Generated by Django 2.2.1 on 2019-08-09 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_smstemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
