# Generated by Django 2.2.1 on 2019-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_sms_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
