# Generated by Django 2.2.1 on 2019-10-22 09:13

import absolutum.mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20190927_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('proxy', models.CharField(max_length=128, verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Тест',
                'ordering': ['-time_created'],
                'default_permissions': (),
                'verbose_name_plural': 'Тест',
                'permissions': [],
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
