# Generated by Django 2.2.1 on 2019-06-16 14:17

import absolutum.mixins.mixins
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Предоплата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Начало сеанса')),
                ('finish_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Конец сеанса')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отказ'), ('done', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус сделки')),
            ],
            options={
                'ordering': ['step', 'start_datetime'],
                'verbose_name_plural': 'Сделки',
                'permissions': [('add_deal', 'Добавлять сделки'), ('change_deal', 'Редактировать сделки'), ('delete_deal', 'Удалять сделки'), ('view_deal', 'Просматривать сделки')],
                'default_permissions': (),
                'verbose_name': 'Сделка',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='DealComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['-time_created'],
                'verbose_name_plural': 'Комментарии к сделкам',
                'default_permissions': (),
                'verbose_name': 'Комментарий к сделке',
            },
        ),
        migrations.CreateModel(
            name='DealPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=True, verbose_name='Основной')),
                ('control', models.BooleanField(default=False, verbose_name='Контроль')),
            ],
            options={
                'ordering': ['-primary'],
                'verbose_name_plural': 'Привязки к персонам',
                'default_permissions': (),
                'verbose_name': 'Привязка к персоне',
            },
        ),
        migrations.CreateModel(
            name='DealTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_planned', models.DateTimeField(verbose_name='Запланированное время')),
                ('time_completed', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отменена'), ('done', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус задачи')),
            ],
            options={
                'ordering': ['time_planned', 'title'],
                'verbose_name_plural': 'Задачи',
                'permissions': [('add_dealtask', 'Добавлять задачи по сделке'), ('change_dealtask', 'Редактировать задачи по сделке'), ('delete_dealtask', 'Удалять задачи по сделке'), ('view_dealtask', 'Просматривать задачи по сделке')],
                'default_permissions': (),
                'verbose_name': 'Задача',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='DealWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'ordering': ['-time_created'],
                'verbose_name_plural': 'Рабочие процессы по сделкам',
                'default_permissions': (),
                'verbose_name': 'Рабочий процесс по сделке',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeal',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Предоплата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Начало сеанса')),
                ('finish_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Конец сеанса')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отказ'), ('done', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус сделки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Сделка',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDealComment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Комментарий к сделке',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDealPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('primary', models.BooleanField(default=True, verbose_name='Основной')),
                ('control', models.BooleanField(default=False, verbose_name='Контроль')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Привязка к персоне',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDealTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_planned', models.DateTimeField(verbose_name='Запланированное время')),
                ('time_completed', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отменена'), ('done', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус задачи')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Задача',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDealWorkflow',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Рабочий процесс по сделке',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
                ('interval_time', models.TimeField(blank=True, null=True, verbose_name='Интервал')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Услуга',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Шаблон услуги',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Шаблоны услуг',
                'permissions': [('add_servicetemplate', 'Добавлять шаблоны сделки'), ('change_servicetemplate', 'Редактировать шаблоны сделки'), ('delete_servicetemplate', 'Удалять шаблоны сделки'), ('view_servicetemplate', 'Просматривать шаблоны сделки')],
                'default_permissions': (),
                'verbose_name': 'Шаблон услуги',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='ServiceTemplateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('primary', models.BooleanField(default=False, verbose_name='Основная')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='deal.ServiceTemplate', verbose_name='Шаблон')),
            ],
            options={
                'ordering': ['template', 'name'],
                'verbose_name_plural': 'Шаблоны услуг: виды услуг',
                'permissions': [('add_servicetemplatetype', 'Добавлять шаблоны сделки: вид услуги'), ('change_servicetemplatetype', 'Редактировать шаблоны сделки: вид услуги'), ('delete_servicetemplatetype', 'Удалять шаблоны сделки: вид услуги'), ('view_servicetemplatetype', 'Просматривать шаблоны сделки: вид услуги')],
                'default_permissions': (),
                'verbose_name': 'Шаблон услуги: вид услуги',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='ServiceTemplateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('step', models.PositiveSmallIntegerField(default=0, verbose_name='Последовательность')),
                ('color', models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('comment', models.CharField(blank=True, max_length=124, null=True, verbose_name='Комментарий')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deal.ServiceTemplate', verbose_name='Шаблон')),
            ],
            options={
                'ordering': ['template', 'step'],
                'verbose_name_plural': 'Шаблоны услуг: этапы',
                'permissions': [('add_servicetemplatestep', 'Добавлять шаблоны сделки: этапы'), ('change_servicetemplatestep', 'Редактировать шаблоны сделки: этапы'), ('delete_servicetemplatestep', 'Удалять шаблоны сделки: этапы'), ('view_servicetemplatestep', 'Просматривать шаблоны сделки: этапы')],
                'default_permissions': (),
                'verbose_name': 'Шаблон услуги: этап',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
                ('interval_time', models.TimeField(blank=True, null=True, verbose_name='Интервал')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old', to='company.Branch', verbose_name='Офис')),
            ],
            options={
                'ordering': ['branch', 'name'],
                'verbose_name_plural': 'Услуги',
                'permissions': [('add_service', 'Добавлять услуги'), ('change_service', 'Редактировать услуги'), ('delete_service', 'Удалять услуги'), ('view_service', 'Просматривать услуги')],
                'default_permissions': (),
                'verbose_name': 'Услуга',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
