# Generated by Django 2.2.1 on 2019-06-16 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20190616_1417'),
        ('identity', '0001_initial'),
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='service_managers', to='company.User', verbose_name='Администраторы'),
        ),
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='service_masters', to='company.User', verbose_name='Правщики'),
        ),
        migrations.AddField(
            model_name='service',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.ServiceTemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='historicalservicetemplate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Branch', verbose_name='Офис'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.ServiceTemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='historicaldealworkflow',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='historicaldealworkflow',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldealperson',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='historicaldealperson',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldealperson',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='identity.Person', verbose_name='Персона'),
        ),
        migrations.AddField(
            model_name='historicaldealcomment',
            name='deal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='historicaldealcomment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Правщик'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Service', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='service_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.ServiceTemplateType', verbose_name='Вид услуги'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.ServiceTemplateStep', verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='dealworkflow',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dealtask',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dealperson',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_persons', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='dealperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_deals', to='identity.Person', verbose_name='Персона'),
        ),
        migrations.AddField(
            model_name='dealcomment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='deal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='company.User', verbose_name='Правщик'),
        ),
        migrations.AddField(
            model_name='deal',
            name='persons',
            field=models.ManyToManyField(through='deal.DealPerson', to='identity.Person'),
        ),
        migrations.AddField(
            model_name='deal',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deal.Service', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='deal',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deal.ServiceTemplateType', verbose_name='Вид услуги'),
        ),
        migrations.AddField(
            model_name='deal',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deal.ServiceTemplateStep', verbose_name='Этап'),
        ),
    ]
