# Generated by Django 2.2.1 on 2019-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190626_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicetimetablegroup',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='servicetimetablegroup',
            name='comment',
        ),
    ]
