# Generated by Django 2.2.1 on 2019-06-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20190626_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicetimetablegroup',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец интервала'),
        ),
        migrations.AlterField(
            model_name='historicalservicetimetablegroup',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало интервала'),
        ),
        migrations.AlterField(
            model_name='servicetimetablegroup',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец интервала'),
        ),
        migrations.AlterField(
            model_name='servicetimetablegroup',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало интервала'),
        ),
    ]
