# Generated by Django 2.2.1 on 2019-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20190628_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отказ'), ('ok', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус сделки'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Отказ'), ('ok', 'Завершена')], default='in_work', max_length=32, verbose_name='Статус сделки'),
        ),
    ]
