# Generated by Django 2.2.1 on 2019-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_auto_20190708_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
    ]
