# Generated by Django 2.2.1 on 2019-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_auto_20190711_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Предоплата'),
        ),
    ]
