# Generated by Django 2.2.1 on 2019-07-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_auto_20190711_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetimetablegroup',
            options={'default_permissions': (), 'ordering': ['timetable', '-start_time'], 'permissions': [('add_servicetimetablegroup', 'Добавлять группы для расписания'), ('change_servicetimetablegroup', 'Редактировать группы для расписания'), ('delete_servicetimetablegroup', 'Удалять группы для расписания'), ('view_servicetimetablegroup', 'Просматривать группы для расписания')], 'verbose_name': 'Услуга: группа для расписания', 'verbose_name_plural': 'Услуги: группы для расписания'},
        ),
    ]
