# Generated by Django 2.2.1 on 2019-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0011_auto_20190716_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Оплачено'),
        ),
    ]
