# Generated by Django 2.2.1 on 2019-07-23 11:54

import absolutum.mixins.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20190616_1417'),
        ('deal', '0012_auto_20190723_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
            ],
            options={
                'permissions': [('add_expense_type', 'Добавлять типы расходов'), ('change_expense_type', 'Редактировать типы расходов'), ('delete_expense_type', 'Удалять типы расходов'), ('view_expense_type', 'Просматривать типы расходов')],
                'verbose_name_plural': 'Типы расходов',
                'verbose_name': 'Тип расходов',
                'ordering': ['name'],
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True, verbose_name='День расхода')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('value', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Расход')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Branch', verbose_name='Офис')),
                ('created_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Создал запись')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.ExpenseType', verbose_name='Тип расходов')),
            ],
            options={
                'verbose_name': 'historical Расход',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True, verbose_name='День расхода')),
                ('time_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('value', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Расход')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.Branch', verbose_name='Офис')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.User', verbose_name='Создал запись')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='deal.ExpenseType', verbose_name='Тип расходов')),
            ],
            options={
                'permissions': [('add_expense', 'Добавлять расходы'), ('change_expense', 'Редактировать расходы'), ('delete_expense', 'Удалять расходы'), ('view_expense', 'Просматривать расходы')],
                'verbose_name_plural': 'Расходы',
                'verbose_name': 'Расход',
                'ordering': ['day', 'time_created'],
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
