# Generated by Django 2.2.1 on 2019-07-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0013_expense_expensetype_historicalexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetype',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('add_expensetype', 'Добавлять типы расходов'), ('change_expensetype', 'Редактировать типы расходов'), ('delete_expensetype', 'Удалять типы расходов'), ('view_expensetype', 'Просматривать типы расходов')], 'verbose_name': 'Тип расходов', 'verbose_name_plural': 'Типы расходов'},
        ),
    ]
