# Generated by Django 2.2.1 on 2019-07-23 14:33

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0017_auto_20190723_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': (), 'ordering': ['day', 'created_at'], 'permissions': [('add_expense', 'Добавлять расходы'), ('change_expense', 'Редактировать расходы'), ('delete_expense', 'Удалять расходы'), ('view_expense', 'Просматривать расходы')], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='created_user',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
