# Generated by Django 2.2.1 on 2019-07-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0019_auto_20190723_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.ExpenseType', verbose_name='Тип расходов'),
        ),
    ]
