# Generated by Django 2.2.1 on 2019-07-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0020_auto_20190723_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'constraints': [],
                'verbose_name_plural': 'Отчеты',
                'verbose_name': 'Отчет',
                'permissions': [],
                'default_permissions': (),
                'proxy': True,
                'indexes': [],
            },
            bases=('deal.deal',),
        ),
    ]
