# Generated by Django 2.2.1 on 2019-07-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0022_auto_20190725_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='created_by',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='historicaldeal',
            old_name='created_by',
            new_name='manager',
        ),
    ]
