# Generated by Django 2.2.1 on 2019-07-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0023_auto_20190725_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_deals', to='company.User', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Организатор'),
        ),
    ]
