# Generated by Django 2.2.1 on 2019-07-27 09:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0026_auto_20190727_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
