# Generated by Django 2.2.1 on 2019-07-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20190730_1223'),
        ('deal', '0028_auto_20190727_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'permissions': [('add_client', 'Добавлять клиентов'), ('change_client', 'Редактировать клиентов'), ('delete_client', 'Удалять клиентов'), ('view_client', 'Просматривать клиентов')],
                'indexes': [],
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
                'constraints': [],
                'proxy': True,
                'default_permissions': (),
            },
            bases=('identity.person',),
        ),
    ]
