# Generated by Django 2.2.1 on 2019-07-31 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0030_auto_20190731_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='interval_time',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='service',
            name='interval_time',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='Интервал'),
        ),
    ]
