# Generated by Django 2.2.1 on 2019-08-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0032_auto_20190801_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='other_type',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Другой тип расходов'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='other_type',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Другой тип расходов'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
