# Generated by Django 2.2.1 on 2019-08-01 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0034_auto_20190801_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='finish_time',
            field=models.TimeField(default=datetime.time(21, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='service',
            name='finish_time',
            field=models.TimeField(default=datetime.time(21, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), null=True, verbose_name='Начало рабочего дня'),
        ),
    ]
