# Generated by Django 2.2.1 on 2019-08-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0035_auto_20190801_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deal.Service', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Service', verbose_name='Филиал'),
        ),
    ]
