# Generated by Django 2.2.1 on 2019-08-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190802_0616'),
        ('deal', '0036_auto_20190801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='default_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Правщик по умолчанию'),
        ),
        migrations.AddField(
            model_name='service',
            name='default_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_default_master', to='company.User', verbose_name='Правщик по умолчанию'),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__group__in': ['Правщики']}, related_name='service_masters', to='company.User', verbose_name='Правщики'),
        ),
    ]
