# Generated by Django 2.2.1 on 2019-08-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0037_auto_20190809_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='default_master',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account__groups__name__in': ['Правщики']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Правщик по умолчанию'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_default_master', to='company.User', verbose_name='Правщик по умолчанию'),
        ),
        migrations.AlterField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Организаторы']}, related_name='service_managers', to='company.User', verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, related_name='service_masters', to='company.User', verbose_name='Правщики'),
        ),
    ]
