# Generated by Django 2.2.1 on 2019-08-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0038_auto_20190809_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetimetable',
            options={'default_permissions': (), 'ordering': ['service__name', '-start_datetime'], 'permissions': [('add_servicetimetable', 'Добавлять расписание для услуг'), ('change_servicetimetable', 'Редактировать расписание для услуг'), ('delete_servicetimetable', 'Удалять расписание для услуг'), ('view_servicetimetable', 'Просматривать расписание для услуг')], 'verbose_name': 'Услуга: расписание', 'verbose_name_plural': 'Услуги: расписание'},
        ),
    ]
