# Generated by Django 2.2.1 on 2019-08-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0039_auto_20190810_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetimetable',
            options={'default_permissions': (), 'ordering': ['service__name', 'start_datetime'], 'permissions': [('add_servicetimetable', 'Добавлять расписание для услуг'), ('change_servicetimetable', 'Редактировать расписание для услуг'), ('delete_servicetimetable', 'Удалять расписание для услуг'), ('view_servicetimetable', 'Просматривать расписание для услуг')], 'verbose_name': 'Услуга: расписание', 'verbose_name_plural': 'Услуги: расписание'},
        ),
        migrations.AlterModelOptions(
            name='servicetimetablegroup',
            options={'default_permissions': (), 'ordering': ['timetable', 'start_time'], 'permissions': [('add_servicetimetablegroup', 'Добавлять группы для расписания'), ('change_servicetimetablegroup', 'Редактировать группы для расписания'), ('delete_servicetimetablegroup', 'Удалять группы для расписания'), ('view_servicetimetablegroup', 'Просматривать группы для расписания')], 'verbose_name': 'Услуга: группа для расписания', 'verbose_name_plural': 'Услуги: группы для расписания'},
        ),
    ]
