# Generated by Django 2.2.1 on 2019-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0040_auto_20190810_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(limit_choices_to={'account__groups__name__in': ['Организаторы']}, related_name='service_managers', to='company.User', verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(limit_choices_to={'account__groups__name__in': ['Правщики']}, related_name='service_masters', to='company.User', verbose_name='Правщики'),
        ),
    ]
