# Generated by Django 2.2.1 on 2019-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190901_1004'),
        ('deal', '0041_auto_20190829_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='departments',
            field=models.ManyToManyField(related_name='expenses', to='company.Department', verbose_name='Отделы'),
        ),
    ]
