# Generated by Django 2.2.1 on 2019-09-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0042_expensetype_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='company.Department', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='company.Branch', verbose_name='Филиал'),
        ),
    ]
