# Generated by Django 2.2.1 on 2019-09-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190901_1004'),
        ('deal', '0043_auto_20190907_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.Department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Department', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='expenses_types', to='company.Department', verbose_name='Отделы'),
        ),
    ]
