# Generated by Django 2.2.1 on 2019-09-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0045_auto_20190907_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealExpense',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Расходы: Правка',
                'verbose_name': 'Расходы: Правка',
                'proxy': True,
                'default_permissions': (),
                'permissions': [('add_dealexpense', 'Добавлять расходы (сделки)'), ('change_dealexpense', 'Редактировать расходы (сделки)'), ('delete_dealexpense', 'Удалять расходы (сделки)'), ('view_dealexpense', 'Просматривать расходы (сделки)')],
                'constraints': [],
            },
            bases=('deal.expense',),
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': (), 'ordering': ['-day'], 'permissions': [('add_expense', 'Добавлять расходы'), ('change_expense', 'Редактировать расходы'), ('delete_expense', 'Удалять расходы'), ('view_expense', 'Просматривать расходы')], 'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='historicalexpense',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Расходы'},
        ),
    ]
