# Generated by Django 2.2.1 on 2019-09-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0046_auto_20190907_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.Branch', verbose_name='Филиал'),
        ),
    ]
