# Generated by Django 2.2.1 on 2019-09-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0047_auto_20190908_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealexpense',
            options={'default_permissions': (), 'permissions': [('add_dealexpense', 'Добавлять расходы (сделки)'), ('change_dealexpense', 'Редактировать расходы (сделки)'), ('delete_dealexpense', 'Удалять расходы (сделки)'), ('view_dealexpense', 'Просматривать расходы (сделки)')], 'verbose_name': 'Расходы (Правка)', 'verbose_name_plural': 'Расходы (Правка)'},
        ),
    ]
