# Generated by Django 2.2.1 on 2019-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0048_auto_20190910_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытый'),
        ),
    ]
