# Generated by Django 2.2.1 on 2019-09-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0049_expensetype_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtask',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Deal', verbose_name='Сделка'),
        ),
    ]
