# Generated by Django 2.2.1 on 2019-09-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0052_auto_20190923_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealcomment',
            options={'default_permissions': (), 'ordering': ['-time_created'], 'verbose_name': 'Комментарий к сделке / клиенту', 'verbose_name_plural': 'Комментарии к сделкам / клиентам'},
        ),
        migrations.AlterModelOptions(
            name='historicaldealcomment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Комментарий к сделке / клиенту'},
        ),
    ]
