# Generated by Django 2.2.1 on 2019-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0053_auto_20190923_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealcomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'verbose_name': 'Комментарий к сделке / клиенту', 'verbose_name_plural': 'Комментарии к сделкам / клиентам'},
        ),
        migrations.RenameField(
            model_name='dealcomment',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='historicaldealcomment',
            old_name='time_created',
            new_name='created_at',
        ),
    ]
