# Generated by Django 2.2.1 on 2019-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0054_auto_20190923_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealcomment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('add_dealcomment', 'Добавлять комментарии'), ('change_dealcomment', 'Редактировать комментарии'), ('delete_dealcomment', 'Удалять комментарии'), ('view_dealcomment', 'Просматривать комментарии')], 'verbose_name': 'Комментарий к сделке / клиенту', 'verbose_name_plural': 'Комментарии к сделкам / клиентам'},
        ),
        migrations.AlterField(
            model_name='servicetimetable',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Организаторы']}, related_name='manager_service_timetables', to='company.User', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='servicetimetable',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, related_name='master_service_timetables', to='company.User', verbose_name='Правщики'),
        ),
    ]
