# Generated by Django 2.2.1 on 2019-09-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0055_auto_20190923_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcomment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deal.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='dealcomment',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deal.Deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Deal', verbose_name='Сделка'),
        ),
    ]
