# Generated by Django 2.2.1 on 2019-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0057_historicalclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclient',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
