# Generated by Django 2.2.1 on 2019-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0058_historicalclient_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
