# Generated by Django 2.2.1 on 2019-09-27 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0060_auto_20190924_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealworkflow',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'verbose_name': 'Рабочий процесс по сделке', 'verbose_name_plural': 'Рабочие процессы по сделкам'},
        ),
        migrations.RemoveField(
            model_name='dealtask',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='dealworkflow',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='historicaldealtask',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='historicaldealworkflow',
            name='time_created',
        ),
        migrations.AddField(
            model_name='dealcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AddField(
            model_name='dealperson',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dealtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AddField(
            model_name='dealworkflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldealcomment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время последнего редактирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldealperson',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время последнего редактирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldealworkflow',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='dealcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='historicaldealcomment',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Время создания'),
        ),
    ]
