# Generated by Django 2.2.1 on 2019-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0061_auto_20190927_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealtask',
            name='type',
            field=models.CharField(blank=True, choices=[('ask_result', 'Узнать о результатах'), ('to_control', 'Пригласить на контроль')], max_length=32, null=True, verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='historicaldealtask',
            name='type',
            field=models.CharField(blank=True, choices=[('ask_result', 'Узнать о результатах'), ('to_control', 'Пригласить на контроль')], max_length=32, null=True, verbose_name='Тип задачи'),
        ),
    ]
