# Generated by Django 2.2.1 on 2019-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0062_auto_20190928_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclient',
            name='sip_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SIP идентификатор'),
        ),
    ]
