# Generated by Django 2.2.1 on 2019-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0063_historicalclient_sip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtask',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='historicaldealtask',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
    ]
