# Generated by Django 2.2.1 on 2019-10-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0064_auto_20191022_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_deals', to='company.User', verbose_name='Правщик'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='master',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account__groups__name__in': ['Правщики']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Правщик'),
        ),
    ]
