# Generated by Django 2.2.1 on 2019-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0065_auto_20191028_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetemplatestep',
            name='comment',
        ),
        migrations.AddField(
            model_name='deal',
            name='paid_non_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Оплачено безналом'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='paid_non_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Оплачено безналом'),
        ),
        migrations.AddField(
            model_name='servicetemplatestep',
            name='label',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='servicetemplatestep',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='servicetemplatestep',
            name='step',
            field=models.SmallIntegerField(default=0, verbose_name='Последовательность'),
        ),
    ]
