# Generated by Django 2.2.1 on 2019-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0066_auto_20191030_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplatestep',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
