# Generated by Django 2.2.1 on 2019-11-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0067_servicetemplatestep_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldealworkflow',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='historicaldealworkflow',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='servicetemplatestep',
            options={'default_permissions': (), 'ordering': ['template', 'number'], 'permissions': [('add_servicetemplatestep', 'Добавлять шаблоны сделки: этапы'), ('change_servicetemplatestep', 'Редактировать шаблоны сделки: этапы'), ('delete_servicetemplatestep', 'Удалять шаблоны сделки: этапы'), ('view_servicetemplatestep', 'Просматривать шаблоны сделки: этапы')], 'verbose_name': 'Шаблон услуги: этап', 'verbose_name_plural': 'Шаблоны услуг: этапы'},
        ),
        migrations.RemoveField(
            model_name='servicetemplatestep',
            name='step',
        ),
        migrations.AddField(
            model_name='servicetemplatestep',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Последовательность'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'account__groups__name__in': ['Организаторы']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_deals', to='company.User', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='historicaldeal',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account__groups__name__in': ['Организаторы']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Организатор'),
        ),
        migrations.DeleteModel(
            name='DealWorkflow',
        ),
        migrations.DeleteModel(
            name='HistoricalDealWorkflow',
        ),
    ]
