# Generated by Django 2.2.1 on 2019-11-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0009_auto_20191117_1236'),
        ('deal', '0068_auto_20191103_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='mlm_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='mlm.Agent', verbose_name='МЛМ-агент'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='mlm_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mlm.Agent', verbose_name='МЛМ-агент'),
        ),
    ]
