# Generated by Django 2.2.1 on 2019-11-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0069_auto_20191118_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaldeal',
            name='status',
        ),
    ]
