# Generated by Django 2.2.1 on 2019-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0070_auto_20191119_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Провал'), ('ok', 'Успешно')], default='in_work', max_length=32, verbose_name='Статус сделки'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('reject', 'Провал'), ('ok', 'Успешно')], default='in_work', max_length=32, verbose_name='Статус сделки'),
        ),
    ]
