# Generated by Django 2.2.1 on 2019-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0071_auto_20191119_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Организаторы']}, related_name='service_managers', to='company.User', verbose_name='Организаторы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, related_name='service_masters', to='company.User', verbose_name='Правщики'),
        ),
        migrations.AlterField(
            model_name='servicetimetablegroup',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__groups__name__in': ['Правщики']}, related_name='timetable_groups', to='company.User', verbose_name='Правщики'),
        ),
    ]
