# Generated by Django 2.2.1 on 2019-12-28 10:04

import absolutum.mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0074_historicalclient_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('add_service', 'Добавлять услуги'), ('change_service', 'Редактировать услуги'), ('delete_service', 'Удалять услуги'), ('view_service', 'Просматривать услуги')], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='interval_time',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='interval_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_time',
        ),
        migrations.CreateModel(
            name='GroupService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('services', models.ManyToManyField(blank=True, related_name='groups', to='deal.Service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name_plural': 'Группы услуг',
                'verbose_name': 'Группа услуг',
                'default_permissions': (),
                'ordering': ['name'],
                'permissions': [('add_groupservice', 'Добавлять группы услуги'), ('change_groupservice', 'Редактировать группы услуги'), ('delete_groupservice', 'Удалять группы услуги'), ('view_groupservice', 'Просматривать группы услуги')],
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
