# Generated by Django 2.2.1 on 2019-12-28 11:29

from django.db import migrations


def set_status_position(apps, schema_editor):
    model_stage = apps.get_model("deal", "Stage")

    for step in apps.get_model("deal", "ServiceTemplateStep").objects.filter(template_id=1):
        stage = model_stage.objects.create(
            name=step.name,
            label=step.label,
            step=step.number,
            color=step.color,
            background_color=step.background_color
        )
        print('created', stage)

    stage_0 = model_stage.objects.get(step=0)
    stage_1 = model_stage.objects.get(step=1)
    stage_2 = model_stage.objects.get(step=2)
    stage_3 = model_stage.objects.get(step=3)
    stage_4 = model_stage.objects.get(step=4)
    stage_5 = model_stage.objects.get(step=5)
    stage_6 = model_stage.objects.get(step=6)

    # Центры и регионы
    apps.get_model("deal", "Deal").objects.filter(step__number=0).update(stage=stage_0)
    apps.get_model("deal", "Deal").objects.filter(step__number=1).update(stage=stage_1)
    apps.get_model("deal", "Deal").objects.filter(step__number=2).update(stage=stage_2)
    apps.get_model("deal", "Deal").objects.filter(step__number=3).update(stage=stage_3)

    # Регионы
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=True, step__number=4) \
        .update(stage=stage_3)
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=True, step__number=5) \
        .update(stage=stage_4)
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=True, step__number=6) \
        .update(stage=stage_5)
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=True, step__number=7) \
        .update(stage=stage_6)

    # Центры
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=False, step__number=4) \
        .update(stage=stage_4)
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=False, step__number=5) \
        .update(stage=stage_5)
    apps.get_model("deal", "Deal").objects.filter(service_type__template__periodic=False, step__number=6) \
        .update(stage=stage_6)

    apps.get_model("deal", "Deal").objects.filter(stage=None).update(stage=stage_6)


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0077_auto_20191228_1114'),
    ]

    operations = [
        migrations.RunPython(set_status_position),
    ]
