# Generated by Django 2.2.1 on 2019-12-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0020_auto_20191228_1036'),
        ('deal', '0078_auto_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_services', to='company.Master', verbose_name='Специалист')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_masters', to='deal.Service', verbose_name='Услуга')),
            ],
            options={
                'default_permissions': (),
                'ordering': [],
                'verbose_name_plural': 'Оказываемые специалистом услуги',
                'verbose_name': 'Оказываемая специалистом услуга',
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceMaster',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Master', verbose_name='Специалист')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.Service', verbose_name='Услуга')),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Оказываемая специалистом услуга',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='masters_new',
            field=models.ManyToManyField(through='deal.ServiceMaster', to='company.Master', verbose_name='Специалисты'),
        ),
    ]
