# Generated by Django 2.2.1 on 2019-12-28 11:29

from django.db import migrations


def set_status_position(apps, schema_editor):
    model_branch = apps.get_model("company", "Branch")

    for branch in model_branch.objects.all().order_by('name'):
        for service in branch.services.all():
            for i in service.managers.all():
                branch.managers.add(i.id)
            for i in service.masters.all():
                branch.workers.add(i.id)
            if service.timetables.last():
                branch.address = service.timetables.last().address
        branch.save()


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0079_auto_20191228_1228'),
    ]

    operations = [
        migrations.RunPython(set_status_position),
    ]
