# Generated by Django 2.2.1 on 2019-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0080_auto_branch_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='masters_new',
            new_name='masters_n',
        ),
        migrations.RemoveField(
            model_name='groupservice',
            name='services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='masters',
        ),
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='deal.Service', verbose_name='Группа услуг'),
        ),
    ]
