# Generated by Django 2.2.1 on 2019-12-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20191228_1305'),
        ('deal', '0082_auto_20191228_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.Branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='historicaldeal',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.Branch', verbose_name='Филиал'),
        ),
    ]
