# Generated by Django 2.2.1 on 2019-12-28 13:26

from django.db import migrations


def set_branch(apps, schema_editor):
    for deal in apps.get_model("deal", "Deal").objects.all():
        deal.branch = deal.service.branch
        deal.save()
        print(deal, deal.branch)


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0083_auto_20191228_1326'),
    ]

    operations = [
        migrations.RunPython(set_branch),
    ]
