# Generated by Django 2.2.1 on 2019-12-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0084_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservice',
            name='template',
        ),
        migrations.RemoveField(
            model_name='service',
            name='template',
        ),
    ]
