# Generated by Django 2.2.1 on 2019-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0085_auto_20191228_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='deal.GroupService', verbose_name='Группа услуг'),
        ),
    ]
