# Generated by Django 2.2.1 on 2019-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0086_auto_20191228_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(related_name='services', to='deal.GroupService', verbose_name='Группа услуг'),
        ),
    ]
