# Generated by Django 2.2.1 on 2019-12-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0087_auto_20191228_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(null=True, through='deal.ServiceMaster', to='company.Master', verbose_name='Специалисты'),
        ),
    ]
