# Generated by Django 2.2.1 on 2019-12-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0089_auto_20191228_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='groups',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='deal.GroupService', verbose_name='Группа услуг'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='deal.GroupService', verbose_name='Группа услуг'),
        ),
    ]
