# Generated by Django 2.2.1 on 2019-12-29 08:58

import os
import logging
from django.db import migrations
from django.core import serializers

LOGGER = logging.getLogger(__name__)


def load_fixture(apps, schema_editor):
    original_apps = serializers.python.apps
    serializers.python.apps = apps
    fixture_file = './deal/fixtures/GroupService.json'
    fixture = open(fixture_file)
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()
    serializers.python.apps = original_apps


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0090_auto_20191228_1355'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
