# Generated by Django 2.2.1 on 2019-12-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0091_GroupService'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='service',
        ),
        migrations.RemoveField(
            model_name='historicaldeal',
            name='service',
        ),
    ]
