# Generated by Django 2.2.1 on 2019-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0093_auto_20191229_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='cost_kid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость (ребенок)'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность процедуры'),
        ),
        migrations.AddField(
            model_name='historicalservicemaster',
            name='cost_kid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость (ребенок)'),
        ),
        migrations.AddField(
            model_name='historicalservicemaster',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность процедуры'),
        ),
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_kid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость (ребенок)'),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность процедуры'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='cost_kid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость (ребенок)'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность процедуры'),
        ),
    ]
