# Generated by Django 2.2.1 on 2019-12-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0094_auto_20191229_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'ordering': ['group', 'name'], 'permissions': [('add_service', 'Добавлять услуги'), ('change_service', 'Редактировать услуги'), ('delete_service', 'Удалять услуги'), ('view_service', 'Просматривать услуги')], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
