# Generated by Django 2.2.1 on 2019-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0095_auto_20191229_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'default_permissions': (), 'ordering': ['start_datetime'], 'permissions': [('add_deal', 'Добавлять сделки'), ('change_deal', 'Редактировать сделки'), ('delete_deal', 'Удалять сделки'), ('view_deal', 'Просматривать сделки')], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='step',
        ),
        migrations.RemoveField(
            model_name='historicaldeal',
            name='step',
        ),
        migrations.AddField(
            model_name='deal',
            name='services',
            field=models.ManyToManyField(to='deal.Service', verbose_name='Услуги'),
        ),
    ]
