# Generated by Django 2.2.1 on 2019-12-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0097_auto_20191229_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaldeal',
            name='status',
        ),
    ]
