# Generated by Django 2.2.1 on 2019-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0099_auto_20191229_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='services', through='deal.ServiceMaster', to='company.Master', verbose_name='Специалисты'),
        ),
    ]
