# Generated by Django 2.2.1 on 2019-12-29 10:16

from django.core import serializers
from django.db import connection, migrations
import os
import logging

LOGGER = logging.getLogger(__name__)


def load_fixture(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute("TRUNCATE TABLE deal_service cascade")

    original_apps = serializers.python.apps
    serializers.python.apps = apps
    fixture_file = './deal/fixtures/Service.json'
    fixture = open(fixture_file)
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()
    serializers.python.apps = original_apps


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0030_copy_timetables'),
        ('deal', '0101_auto_20191229_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
        migrations.RunPython(load_fixture),
    ]
