# Generated by Django 2.2.1 on 2019-12-28 13:26

from django.db import migrations


def set_branch(apps, schema_editor):
    for deal in apps.get_model("deal", "Deal").objects.all():
        service = 1
        service_type = deal.service_type_id
        if service_type in [9, 10]:
            service = 2
        if service_type in [11]:
            service = 3
        deal.services.add(service)
        deal.save()
        print(deal, deal.branch)


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0102_Service'),
    ]

    operations = [
        migrations.RunPython(set_branch),
        migrations.RemoveField(
            model_name='deal',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='historicaldeal',
            name='service_type',
        ),
    ]
