# Generated by Django 2.2.1 on 2020-01-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0103_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetemplatestep',
            name='template',
        ),
        migrations.RemoveField(
            model_name='servicetemplatetype',
            name='template',
        ),
        migrations.DeleteModel(
            name='HistoricalServiceTemplate',
        ),
        migrations.DeleteModel(
            name='ServiceTemplate',
        ),
        migrations.DeleteModel(
            name='ServiceTemplateStep',
        ),
        migrations.DeleteModel(
            name='ServiceTemplateType',
        ),
    ]
