# Generated by Django 2.2.1 on 2020-02-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0106_auto_20200212_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupService',
            new_name='ServiceGroup',
        ),
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('add_servicegroup', 'Добавлять группы услуги'), ('change_servicegroup', 'Редактировать группы услуги'), ('delete_servicegroup', 'Удалять группы услуги'), ('view_servicegroup', 'Просматривать группы услуги')], 'verbose_name': 'Группа услуг', 'verbose_name_plural': 'Группы услуг'},
        ),
    ]
