# Generated by Django 2.2.1 on 2020-02-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0107_auto_20200218_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicemaster',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='historicalservicemaster',
            name='cost_kid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Стоимость (ребенок)'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='cost_kid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Стоимость (ребенок)'),
        ),
    ]
