# Generated by Django 2.2.1 on 2020-02-18 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0108_auto_20200218_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemaster',
            options={'default_permissions': (),
                     'permissions': [
                         ('add_servicemaster', 'Добавлять услуги специалиста'),
                         ('change_servicemaster', 'Редактировать услуги специалиста'),
                         ('delete_servicemaster', 'Удалять услуги специалиста'),
                         ('view_servicemaster', 'Просматривать услуги специалиста')
                     ],
                     'ordering': [],
                     'verbose_name': 'Оказываемая специалистом услуга',
                     'verbose_name_plural': 'Оказываемые специалистом услуги'},
        ),
        migrations.RemoveField(
            model_name='historicalservicemaster',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='deleted',
        ),
    ]
