# Generated by Django 2.2.1 on 2020-02-18 10:50

from django.db import migrations


def del_service(apps, schema_editor):
    pravka = apps.get_model("deal", "Service").objects.filter(name='Правка').first()
    control = apps.get_model("deal", "Service").objects.filter(name='Контроль').first()
    for deal in apps.get_model("deal", "Deal").objects.filter(services=control):
        deal.services.remove(control)
        deal.services.add(pravka)
        deal.save()
        print(deal.id)
        deal.rel_persons.update(control=True)


class Migration(migrations.Migration):
    dependencies = [
        ('deal', '0109_auto_20200218_1035'),
    ]

    operations = [
        migrations.RunPython(del_service),
    ]
