# Generated by Django 2.2.1 on 2020-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0111_auto_20200225_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicemaster',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='historicalservicemaster',
            name='reward_percent',
            field=models.BooleanField(default=False, verbose_name='Вознаграждение: процент'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='reward_percent',
            field=models.BooleanField(default=False, verbose_name='Вознаграждение: процент'),
        ),
    ]
