# Generated by Django 2.2.1 on 2020-03-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_auto_20200304_1707'),
        ('deal', '0112_auto_20200304_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicemaster',
            unique_together={('service', 'master')},
        ),
    ]
