# Generated by Django 2.2.1 on 2019-10-11 12:30

import absolutum.mixins.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_manager_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Входящий'), ('outcoming', 'Исходящий')], default='outcoming', max_length=32, verbose_name='Тип звонка')),
                ('sip_id', models.CharField(max_length=32, null=True, verbose_name='SIP индентификатор')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='Кому звонок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда звонили')),
                ('result', models.CharField(max_length=512, verbose_name='Результат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_logs', to='company.User', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name_plural': 'Журнал',
                'permissions': [('view_log', 'Просматривать журнал')],
                'ordering': ['-created_at'],
                'default_permissions': (),
                'verbose_name': 'Запись в журнале',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
