# Generated by Django 2.2.1 on 2019-10-13 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
