# Generated by Django 2.2.1 on 2019-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_log_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='type',
        ),
        migrations.AddField(
            model_name='log',
            name='event',
            field=models.CharField(default='outcoming', max_length=32, verbose_name='Тип звонка'),
        ),
    ]
