# Generated by Django 2.2.1 on 2019-12-08 11:00

import absolutum.mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0005_remove_log_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='MightyCallUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('user_key', models.CharField(help_text='Добавочный номер либо сгенерированный ключ пользователя', max_length=256, verbose_name='Добавочный номер (ключ)')),
                ('display_number', models.CharField(max_length=18, verbose_name='Отображаемый номер')),
                ('token', models.CharField(max_length=1024, verbose_name='Токен')),
                ('token_type', models.CharField(max_length=256, verbose_name='Тип токена')),
                ('token_expires', models.DateTimeField(blank=True, help_text='Время смерти текущего токена', null=True, verbose_name='Токен действует до')),
                ('token_refresh', models.CharField(help_text='Токен для перегенерации ранее выданного токена', max_length=256, verbose_name='Токен перегенерации')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('add_user', 'Добавлять пользователей яндекс.телефонии'), ('change_user', 'Редактировать пользователей яндекс.телефонии'), ('delete_user', 'Удалять пользователей яндекс.телефонии'), ('view_user', 'Просматривать пользователей яндекс.телефонии')],
                'verbose_name': 'Пользователь яндекс.телефонии',
                'default_permissions': (),
                'verbose_name_plural': 'Пользователи яндекс.телефонии',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
