# Generated by Django 2.2.1 on 2019-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0007_auto_20191208_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mightycalluser',
            name='display_number',
            field=models.CharField(max_length=18, null=True, verbose_name='Отображаемый номер'),
        ),
        migrations.AlterField(
            model_name='mightycalluser',
            name='token',
            field=models.CharField(max_length=1024, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='mightycalluser',
            name='token_refresh',
            field=models.CharField(help_text='Токен для перегенерации ранее выданного токена', max_length=256, null=True, verbose_name='Токен перегенерации'),
        ),
        migrations.AlterField(
            model_name='mightycalluser',
            name='token_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Тип токена'),
        ),
    ]
