# Generated by Django 2.2.1 on 2019-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0009_auto_20191208_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mightycalluser',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Токен'),
        ),
    ]
