# Generated by Django 2.2.1 on 2019-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0011_auto_20191208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mightycalluser',
            name='extension_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Добавочный номер'),
        ),
    ]
