# Generated by Django 2.2.1 on 2019-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0013_auto_20191212_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mightycalluser',
            name='extension_number',
            field=models.CharField(default=None, max_length=18, verbose_name='Добавочный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mightycalluser',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='mightycalluser',
            name='user_key',
            field=models.CharField(blank=True, help_text='Сгенерированный ключ пользователя', max_length=256, null=True, verbose_name='Ключ пользователя'),
        ),
    ]
