# Generated by Django 2.2.1 on 2019-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0014_auto_20191215_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mightycalluser',
            name='user_key',
            field=models.CharField(default=None, help_text='Сгенерированный ключ пользователя', max_length=256, verbose_name='Ключ пользователя'),
            preserve_default=False,
        ),
    ]
