# Generated by Django 2.2.1 on 2019-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0016_auto_20191215_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('view_log', 'Просматривать журнал')], 'verbose_name': 'Запись в журнале телефонии', 'verbose_name_plural': 'Журнал телефонии'},
        ),
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.CharField(max_length=32, verbose_name='Тип события'),
        ),
    ]
