# Generated by Django 2.2.1 on 2019-12-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0017_auto_20191215_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='event',
            new_name='event_type',
        ),
    ]
