# Generated by Django 2.2.1 on 2019-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0019_auto_20191215_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Запись создана'),
        ),
    ]
