# Generated by Django 2.2.1 on 2019-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0020_auto_20191215_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='entry_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Id звонка'),
        ),
    ]
