# Generated by Django 2.2.1 on 2019-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0021_log_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='entry_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='log',
            name='from_number',
            field=models.CharField(max_length=256, null=True, verbose_name='Кто звонил'),
        ),
        migrations.AlterField(
            model_name='log',
            name='to_number',
            field=models.CharField(max_length=256, null=True, verbose_name='Набранный номер'),
        ),
    ]
