# Generated by Django 2.2.1 on 2019-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20190711_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'соц.сеть'), (2, 'мессенджер')], default=1, null=True, verbose_name='Тип контакта'),
        ),
    ]
