# Generated by Django 2.2.1 on 2019-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20190711_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, ''), (2, 'соц.сеть'), (3, 'мессенджер')], default=1, verbose_name='Тип контакта'),
        ),
    ]
