# Generated by Django 2.2.1 on 2019-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_auto_20190711_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, ' '), (1, 'соц.сеть'), (2, 'мессенджер')], default=0, verbose_name='Тип контакта'),
        ),
    ]
