# Generated by Django 2.2.1 on 2019-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20190730_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='timezone',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='person',
            name='timezone',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Часовой пояс'),
        ),
    ]
