# Generated by Django 2.2.1 on 2019-08-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_auto_20190802_0616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
