# Generated by Django 2.2.1 on 2019-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_auto_20190813_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'patronymic', 'last_name', 'birthday')},
        ),
    ]
