# Generated by Django 2.2.1 on 2019-08-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_auto_20190823_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
