# Generated by Django 2.2.1 on 2019-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_auto_20190824_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'patronymic', 'last_name', 'birthday')},
        ),
    ]
