# Generated by Django 2.2.1 on 2019-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_auto_20190825_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
