# Generated by Django 2.2.1 on 2019-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_auto_20191208_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='token',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
