# Generated by Django 2.2.1 on 2020-01-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_auto_20191221_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
