# Generated by Django 2.2.1 on 2020-02-22 15:20

import absolutum.mixins.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_auto_20200123_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFamilyRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'отец'), (1, 'мать')], default=0, verbose_name='Отношения')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='identity.Person', verbose_name='Родственные связи')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='identity.Person', verbose_name='Родственник')),
            ],
            options={
                'verbose_name': 'Семейные связи',
                'verbose_name_plural': 'Семейные связи',
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
