# Generated by Django 2.2.1 on 2020-02-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_personfamilyrelations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfamilyrelations',
            old_name='type',
            new_name='relative_type',
        ),
    ]
