# Generated by Django 2.2.1 on 2019-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20190730_1223'),
        ('company', '0002_auto_20190616_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisplay',
            fields=[
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Персонал',
                'constraints': [],
                'indexes': [],
                'proxy': True,
                'verbose_name_plural': 'Персонал',
                'permissions': [('add_userdisplay', 'Добавлять персонал'), ('change_userdisplay', 'Редактировать персонал'), ('delete_userdisplay', 'Удалять персонал'), ('view_userdisplay', 'Просматривать персонал')],
            },
            bases=('identity.person',),
        ),
    ]
