# Generated by Django 2.2.1 on 2019-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_userdisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
