# Generated by Django 2.2.1 on 2019-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190801_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон'),
        ),
    ]
