# Generated by Django 2.2.1 on 2019-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_department_historicaldepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdisplay',
            options={'default_permissions': (), 'permissions': [('add_userdisplay', 'Добавлять персонал'), ('change_userdisplay', 'Редактировать персонал'), ('delete_userdisplay', 'Удалять персонал'), ('view_userdisplay', 'Просматривать персонал')], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
