# Generated by Django 2.2.1 on 2019-10-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20191025_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltimetable',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Табель учета рабочего времени'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'default_permissions': (), 'ordering': [], 'permissions': [('add_timetable', 'Добавлять табель'), ('change_timetable', 'Редактировать табель'), ('delete_timetable', 'Удалять табель'), ('view_timetable', 'Просматривать табель')], 'verbose_name': 'Табель учета рабочего времени', 'verbose_name_plural': 'Табель учета рабочего времени'},
        ),
    ]
