# Generated by Django 2.2.1 on 2019-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20191028_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='company.User', verbose_name='Персонал'),
        ),
    ]
