# Generated by Django 2.2.1 on 2019-11-09 08:38

from django.db import migrations


def set_status_position(apps, schema_editor):
    users = apps.get_model("identity", "account")
    users.objects.filter(is_active=True).update(is_staff=True)


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0015_auto_20191109_0837'),
    ]
    operations = [
        migrations.RunPython(set_status_position),
    ]
