# Generated by Django 2.2.1 on 2020-01-13 10:01

import absolutum.mixins.mixins
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0016_auto_20191109_0838_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='Тип события')),
                ('event', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('event_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время события')),
                ('cache', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'permissions': [('add_eventlog', 'Добавлять журнал событий'), ('change_eventlog', 'Редактировать журнал событий'), ('delete_eventlog', 'Удалять журнал событий'), ('view_eventlog', 'Просматривать журнал событий')],
                'verbose_name': 'Журнал событий',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-event_datetime'],
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
