# Generated by Django 2.2.1 on 2019-12-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_branch_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'default_permissions': (), 'permissions': [], 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
    ]
