# Generated by Django 2.2.1 on 2019-12-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20191225_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='branch',
            name='interval_time',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='Интервал'),
        ),
        migrations.AddField(
            model_name='branch',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='interval_time',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='Интервал'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__is_active': True}, related_name='managers', to='company.User', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='workers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__is_active': True}, related_name='workers', to='company.User', verbose_name='Персонал'),
        ),
    ]
