# Generated by Django 2.2.1 on 2019-12-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20191228_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'default_permissions': (), 'permissions': [], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
