# Generated by Django 2.2.1 on 2019-12-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20191228_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='interval_time',
        ),
        migrations.RemoveField(
            model_name='historicalbranch',
            name='interval_time',
        ),
    ]
