# Generated by Django 2.2.1 on 2019-12-28 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20191228_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0), null=True, verbose_name='Конец рабочего дня'),
        ),
    ]
