# Generated by Django 2.2.1 on 2019-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20191228_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='managers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__is_active': True}, related_name='manager_branches', to='company.User', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='workers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__is_active': True}, related_name='worker_branches', to='company.User', verbose_name='Персонал'),
        ),
    ]
