# Generated by Django 2.2.1 on 2020-01-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20191229_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='company.Branch', verbose_name='Филиал'),
        ),
    ]
