# Generated by Django 2.2.1 on 2020-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20200110_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltimegroup',
            old_name='finish_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='timegroup',
            old_name='finish_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='historicaltimegroup',
            name='end_datetime',
            field=models.DateTimeField(default=None, verbose_name='Конец периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltimegroup',
            name='start_datetime',
            field=models.DateTimeField(default=None, verbose_name='Начало периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timegroup',
            name='end_datetime',
            field=models.DateTimeField(default=None, verbose_name='Конец периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timegroup',
            name='start_datetime',
            field=models.DateTimeField(default=None, verbose_name='Начало периода'),
            preserve_default=False,
        ),
    ]
