# Generated by Django 2.2.1 on 2020-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20200112_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimegroup',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='historicaltimegroup',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='timegroup',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='timegroup',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='historicaltimegroup',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Конец периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltimegroup',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Начало периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timegroup',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Конец периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timegroup',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Начало периода'),
            preserve_default=False,
        ),
    ]
