# Generated by Django 2.2.1 on 2020-01-10 14:23

from django.db import migrations, models


def load_fixture(apps, schema_editor):
    _groups = []
    group_model = apps.get_model("company", "TimeGroup")
    for group in apps.get_model("deal", "ServiceTimetableGroup").objects.all():
        _groups.append(dict(
            branch=group.timetable.service.branch,
            name=group.name,
            start_date=group.timetable.start_datetime.date(),
            end_date=group.timetable.finish_datetime.date(),
            start_time=group.start_time,
            end_time=group.finish_time,
        ))
    group_model.objects.bulk_create([group_model(**data) for data in _groups])


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0029_auto_20200112_0853'),
        # ('deal', '0099_auto_20191229_1141.py'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
