# Generated by Django 2.2.1 on 2020-01-12 09:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_copy_timetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
