# Generated by Django 2.2.1 on 2020-01-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20200112_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timegroup',
            options={'default_permissions': (), 'ordering': ['branch', 'start_date', 'end_date', 'start_time'], 'permissions': [('add_timegroup', 'Добавлять группы для расписания'), ('change_timegroup', 'Редактировать группы для расписания'), ('delete_timegroup', 'Удалять группы для расписания'), ('view_timegroup', 'Просматривать группы для расписания')], 'verbose_name': 'Группа в расписании', 'verbose_name_plural': 'Группы для расписания'},
        ),
    ]
