# Generated by Django 2.2.1 on 2020-01-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20200112_1659'),
        ('company', '0017_eventlog'),
    ]

    operations = [
    ]
