# Generated by Django 2.2.1 on 2020-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_auto_20200130_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltimegroup',
            name='delay',
            field=models.BooleanField(default=False, verbose_name='Перерыв'),
        ),
        migrations.AddField(
            model_name='timegroup',
            name='delay',
            field=models.BooleanField(default=False, verbose_name='Перерыв'),
        ),
    ]
