# Generated by Django 2.2.1 on 2020-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_auto_20200207_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltimegroup',
            name='end_date',
            field=models.DateField(verbose_name='Конец периода (день)'),
        ),
        migrations.AlterField(
            model_name='historicaltimegroup',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='Конец интервала (время)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltimegroup',
            name='start_date',
            field=models.DateField(verbose_name='Начало периода (день)'),
        ),
        migrations.AlterField(
            model_name='historicaltimegroup',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='Начало интервала (время)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timegroup',
            name='end_date',
            field=models.DateField(verbose_name='Конец периода (день)'),
        ),
        migrations.AlterField(
            model_name='timegroup',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='Конец интервала (время)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timegroup',
            name='start_date',
            field=models.DateField(verbose_name='Начало периода (день)'),
        ),
        migrations.AlterField(
            model_name='timegroup',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='Начало интервала (время)'),
            preserve_default=False,
        ),
    ]
