# Generated by Django 2.2.1 on 2020-02-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_auto_20200207_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltimegroup',
            old_name='delay',
            new_name='timeout',
        ),
        migrations.RenameField(
            model_name='timegroup',
            old_name='delay',
            new_name='timeout',
        ),
    ]
