# Generated by Django 2.2.1 on 2020-02-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_auto_20200208_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='timegroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='time_groups', to='company.User', verbose_name='Персонал'),
        ),
    ]
