# Generated by Django 2.2.1 on 2020-02-11 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_auto_20200210_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 15), null=True, verbose_name='Интервал'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 15), null=True, verbose_name='Интервал'),
        ),
    ]
