# Generated by Django 2.2.1 on 2020-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_auto_20200211_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='periodic',
            field=models.BooleanField(default=True, verbose_name='Периодический'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='periodic',
            field=models.BooleanField(default=True, verbose_name='Периодический'),
        ),
    ]
