# Generated by Django 2.2.1 on 2020-02-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_auto_20200211_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'default_permissions': (), 'permissions': [], 'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
    ]
