# Generated by Django 2.2.1 on 2019-11-09 13:32

import absolutum.mixins.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0016_auto_20191011_1527'),
        ('company', '0016_auto_20191109_0838_user_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0068_auto_20191103_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True, verbose_name='Токен')),
                ('code', models.CharField(max_length=32, null=True, unique=True, verbose_name='Кодовое слово')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_agent', to='identity.Person', verbose_name='Персона')),
            ],
            options={
                'permissions': [('add_agent', 'Добавлять МЛМ-агентов'), ('change_agent', 'Редактировать МЛМ-агентов'), ('delete_agent', 'Удалять МЛМ-агентов'), ('view_agent', 'Просматривать МЛМ-агентов')],
                'verbose_name': 'МЛМ-агент',
                'verbose_name_plural': 'МЛМ-агенты',
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='Процент')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выплаты')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='mlm.Agent', verbose_name='Агент')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_invite', to='deal.Deal', verbose_name='Сделка')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_payouts', to='company.User', verbose_name='Инициатор выплаты')),
            ],
            options={
                'permissions': [('view_invite', 'Просматривать МЛМ-приглашения')],
                'verbose_name': 'МЛМ-приглашение',
                'verbose_name_plural': 'МЛМ-приглашения',
                'default_permissions': (),
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
        migrations.CreateModel(
            name='HistoricalAgent',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True, verbose_name='Токен')),
                ('code', models.CharField(db_index=True, max_length=32, null=True, verbose_name='Кодовое слово')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='identity.Person', verbose_name='Персона')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical МЛМ-агент',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
