# Generated by Django 2.2.1 on 2019-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'default_permissions': (), 'permissions': [('view_invite_send', 'Отправлять МЛМ-приглашения'), ('view_invite', 'Просматривать МЛМ-приглашения')], 'verbose_name': 'МЛМ-приглашение', 'verbose_name_plural': 'МЛМ-приглашения'},
        ),
        migrations.AddField(
            model_name='agent',
            name='level_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AddField(
            model_name='agent',
            name='level_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AddField(
            model_name='agent',
            name='level_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 3 уровень'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='level_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='level_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='level_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Процент за 3 уровень'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='token',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='Токен'),
        ),
    ]
