# Generated by Django 2.2.1 on 2019-11-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_auto_20191111_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'default_permissions': (), 'permissions': [('view_invite', 'Просматривать МЛМ-приглашения'), ('send_invite', 'Отправлять МЛМ-приглашения')], 'verbose_name': 'МЛМ-приглашение', 'verbose_name_plural': 'МЛМ-приглашения'},
        ),
    ]
