# Generated by Django 2.2.1 on 2019-11-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_auto_20191111_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='level_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='level_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='level_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 3 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 3 уровень'),
        ),
    ]
