# Generated by Django 2.2.1 on 2019-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_auto_20191111_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='Промокод'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=32, verbose_name='Промокод'),
            preserve_default=False,
        ),
    ]
