# Generated by Django 2.2.1 on 2019-11-12 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_auto_20191112_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
