# Generated by Django 2.2.1 on 2019-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0007_auto_20191112_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер кредитной карты'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер кредитной карты'),
        ),
    ]
