# Generated by Django 2.2.1 on 2019-11-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0069_auto_20191118_1000'),
        ('mlm', '0009_auto_20191117_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('agent', 'deal')},
        ),
    ]
