# Generated by Django 2.2.1 on 2019-11-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0069_auto_20191118_1000'),
        ('mlm', '0010_auto_20191118_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('deal', 'level')},
        ),
    ]
