# Generated by Django 2.2.1 on 2019-11-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0011_auto_20191118_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='mlm.Agent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='deal.Deal', verbose_name='Сделка'),
        ),
    ]
