# Generated by Django 2.2.1 on 2019-11-18 12:39

import absolutum.mixins.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20191109_0838_user_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlm', '0013_auto_20191118_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAgentPayment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Время выплаты')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mlm.Agent', verbose_name='Агент')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.User', verbose_name='Кто выплатил')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Выплата МЛМ-агенту',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выплаты')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mlm.Agent', verbose_name='Агент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_payments', to='company.User', verbose_name='Кто выплатил')),
            ],
            options={
                'verbose_name_plural': 'Выплаты МЛМ-агентам',
                'default_permissions': (),
                'permissions': [('add_agentpayment', 'Добавлять выплаты МЛМ-агентов'), ('change_agentpayment', 'Редактировать выплаты МЛМ-агентов'), ('delete_agentpayment', 'Удалять выплаты МЛМ-агентов'), ('view_agentpayment', 'Просматривать выплаты МЛМ-агентов')],
                'verbose_name': 'Выплата МЛМ-агенту',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
