# Generated by Django 2.2.1 on 2019-11-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0014_agentpayment_historicalagentpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'default_permissions': (), 'ordering': ['-cache__invite_balance'], 'permissions': [('add_agent', 'Добавлять агентов'), ('change_agent', 'Редактировать агентов'), ('delete_agent', 'Удалять агентов'), ('view_agent', 'Просматривать агентов')], 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='agentpayment',
            options={'default_permissions': (), 'permissions': [('add_agentpayment', 'Добавлять выплаты агентов'), ('change_agentpayment', 'Редактировать выплаты агентов'), ('delete_agentpayment', 'Удалять выплаты агентов'), ('view_agentpayment', 'Просматривать выплаты агентов')], 'verbose_name': 'Выплата агенту', 'verbose_name_plural': 'Выплаты агентам'},
        ),
        migrations.AlterModelOptions(
            name='historicalagent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Агент'},
        ),
        migrations.AlterModelOptions(
            name='historicalagentpayment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Выплата агенту'},
        ),
    ]
