# Generated by Django 2.2.1 on 2019-11-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0015_auto_20191119_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
