# Generated by Django 2.2.1 on 2019-11-19 08:42

import absolutum.mixins.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0071_auto_20191119_0825'),
        ('mlm', '0016_delete_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='Процент')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='mlm.Agent', verbose_name='Агент')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='deal.Deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name_plural': 'МЛМ-приглашения',
                'default_permissions': (),
                'permissions': [('view_invite', 'Просматривать МЛМ-приглашения'), ('send_invite', 'Отправлять МЛМ-приглашения')],
                'unique_together': {('deal', 'level')},
                'verbose_name': 'МЛМ-приглашение',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
