# Generated by Django 2.2.1 on 2019-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0018_auto_20191119_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='agentpayment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='historicalagentpayment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер счета'),
        ),
    ]
