# Generated by Django 2.2.1 on 2019-11-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0020_auto_20191119_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_lead', to='mlm.Agent', verbose_name='Кто привел'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mlm.Agent', verbose_name='Кто привел'),
        ),
    ]
