# Generated by Django 2.2.1 on 2019-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0021_auto_20191119_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('done', 'Выплата')], default='wait', max_length=16, verbose_name='Статус приглашения'),
        ),
    ]
