# Generated by Django 2.2.1 on 2019-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0022_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('ok', 'Выплата')], default='wait', max_length=16, verbose_name='Статус'),
        ),
    ]
