# Generated by Django 2.2.1 on 2019-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0023_auto_20191119_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='historicalagent',
            name='card_number',
        ),
        migrations.AddField(
            model_name='agent',
            name='bank_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='bank_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Реквизиты'),
        ),
    ]
