# Generated by Django 2.2.1 on 2019-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0026_auto_20191130_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='level_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='level_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='level_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 3 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 1 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 2 уровень'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='level_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент за 3 уровень'),
        ),
    ]
