# Generated by Django 2.2.1 on 2020-01-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0028_auto_20200106_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='contract_offer',
            new_name='offer_accepted',
        ),
        migrations.RenameField(
            model_name='historicalagent',
            old_name='contract_offer',
            new_name='offer_accepted',
        ),
    ]
