# Generated by Django 2.2.1 on 2020-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0029_auto_20200106_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bank_account_name',
            field=models.TextField(blank=True, default='', verbose_name='Имя на карте'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='bank_account_name',
            field=models.TextField(blank=True, default='', verbose_name='Имя на карте'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bank_account',
            field=models.TextField(blank=True, default='', verbose_name='Банковская карта'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='bank_account',
            field=models.TextField(blank=True, default='', verbose_name='Банковская карта'),
        ),
    ]
