# Generated by Django 2.2.1 on 2020-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0030_auto_20200108_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя на карте'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя на карте'),
        ),
    ]
