# Generated by Django 2.2.1 on 2020-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0031_auto_20200108_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bank_account',
            field=models.CharField(blank=True, max_length=256, verbose_name='Банковская карта'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='bank_account',
            field=models.CharField(blank=True, max_length=256, verbose_name='Банковская карта'),
        ),
    ]
