# Generated by Django 2.2.1 on 2020-01-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0032_auto_20200108_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='bank_account_name',
            new_name='bank_account_fio',
        ),
        migrations.RenameField(
            model_name='historicalagent',
            old_name='bank_account_name',
            new_name='bank_account_fio',
        ),
    ]
