# Generated by Django 2.2.1 on 2020-01-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0033_auto_20200108_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pretender',
            field=models.BooleanField(default=False, verbose_name='Претендент'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='pretender',
            field=models.BooleanField(default=False, verbose_name='Претендент'),
        ),
    ]
