# Generated by Django 2.2.1 on 2020-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0034_auto_20200109_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='social_link',
            field=models.TextField(blank=True, verbose_name='Страница вконтакте'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='social_link',
            field=models.TextField(blank=True, verbose_name='Страница вконтакте'),
        ),
    ]
