# Generated by Django 2.2.1 on 2020-01-13 10:42

from django.db import migrations, models


def set_ok(apps, schema_editor):
    apps.get_model("mlm", "invite").objects.all().update(status='ok')


class Migration(migrations.Migration):
    dependencies = [
        ('mlm', '0035_auto_20200112_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('ok', 'Выплата')], default='ok', max_length=16,
                                   verbose_name='Статус'),
        ),
        migrations.RunPython(set_ok),
    ]
