# Generated by Django 2.2.1 on 2020-01-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0037_auto_20200113_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalagent',
            old_name='lead',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='lead',
        ),
        migrations.AddField(
            model_name='agent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlm.Agent', verbose_name='Кто привел'),
        ),
    ]
