# Generated by Django 2.2.1 on 2020-01-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0038_auto_20200114_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'default_permissions': (), 'ordering': ['-cache__invite_balance', 'person'], 'permissions': [('add_agent', 'Добавлять агентов'), ('change_agent', 'Редактировать агентов'), ('delete_agent', 'Удалять агентов'), ('view_agent', 'Просматривать агентов'), ('mlm_head', 'МЛМ руководитель'), ('mlm_manager', 'МЛМ менеджер')], 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
    ]
