# Generated by Django 2.2.1 on 2020-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0039_auto_20200121_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.CharField(choices=[('pretender', 'Претендент'), ('agent', 'Агент'), ('manager', 'Менеджер'), ('head', 'Руководитель')], default='in_work', max_length=32, verbose_name='Положение'),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='position',
            field=models.CharField(choices=[('pretender', 'Претендент'), ('agent', 'Агент'), ('manager', 'Менеджер'), ('head', 'Руководитель')], default='in_work', max_length=32, verbose_name='Положение'),
        ),
    ]
