# Generated by Django 2.2.1 on 2020-01-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0041_agent_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='pretender',
        ),
        migrations.RemoveField(
            model_name='historicalagent',
            name='pretender',
        ),
    ]
