# Generated by Django 2.2.1 on 2020-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0044_agentturnover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='parent',
            new_name='referral',
        ),
        migrations.RenameField(
            model_name='historicalagent',
            old_name='parent',
            new_name='referral',
        ),
        migrations.AlterField(
            model_name='agentturnover',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=30, verbose_name='Начислено'),
        ),
    ]
