# Generated by Django 2.2.1 on 2020-01-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0046_auto_20200125_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_agent', to='identity.Person', verbose_name='Персона'),
        ),
    ]
