# Generated by Django 2.2.1 on 2020-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0052_auto_20200127_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentturnover',
            name='new_agents',
            field=models.IntegerField(default=0, verbose_name='Подключено агентов'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='position',
            field=models.CharField(choices=[('pretender', 'Претендент'), ('agent', 'Агент'), ('manager', 'Менеджер'), ('head', 'Руководитель')], default='agent', max_length=32, verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='historicalagent',
            name='position',
            field=models.CharField(choices=[('pretender', 'Претендент'), ('agent', 'Агент'), ('manager', 'Менеджер'), ('head', 'Руководитель')], default='agent', max_length=32, verbose_name='Положение'),
        ),
    ]
