# Generated by Django 2.2.1 on 2019-06-16 14:17

import absolutum.mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=124, null=True, verbose_name='Наименование')),
                ('timezone', models.SmallIntegerField(blank=True, default=0, verbose_name='Часовой пояс')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Города',
                'permissions': [('add_city', 'Добавлять города'), ('change_city', 'Редактировать города'), ('delete_city', 'Удалять города'), ('view_city', 'Просматривать города')],
                'default_permissions': (),
                'verbose_name': 'Город',
            },
            bases=(models.Model, absolutum.mixins.mixins.CoreMixin, absolutum.mixins.mixins.DisplayMixin),
        ),
    ]
