# Generated by Django 2.2.1 on 2019-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='short',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=None, max_length=124, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
