# Generated by Django 2.2.1 on 2019-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20190727_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=124, unique=True, verbose_name='Наименование'),
        ),
    ]
