# Generated by Django 2.2.1 on 2019-08-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20190731_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='position',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Сортировка'),
        ),
    ]
