# Generated by Django 2.2.1 on 2019-11-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_city_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'ordering': ['-position', 'name'], 'permissions': [('add_city', 'Добавлять города'), ('change_city', 'Редактировать города'), ('delete_city', 'Удалять города'), ('view_city', 'Просматривать города')], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
