# Generated by Django 2.2.1 on 2019-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_workingdayscalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdayscalendar',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
